#!/usr/bin/env bash
# install.sh - Install network diagnostics on a Raspberry Pi
# 
# Usage: 
#   scp -r /path/to/network-diagnostics pi@<pi-ip>:/home/pi/netdiag
#   ssh pi@<pi-ip> "bash /home/pi/netdiag/install.sh"
#
# Or run locally after copying files:
#   bash /home/pi/netdiag/install.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="/var/log/netdiag"
CONFIG_DIR="/etc/netdiag"

echo "=========================================="
echo "  Network Diagnostics Installer"
echo "=========================================="
echo ""

# Detect network interface
detect_interface() {
  if ip link show wlan0 &>/dev/null; then
    echo "wlan0"
  elif ip link show eth0 &>/dev/null; then
    echo "eth0"
  else
    echo "unknown"
  fi
}

IFACE=$(detect_interface)
IS_WIFI=false
[[ "$IFACE" == "wlan0" ]] && IS_WIFI=true

echo "Detected interface: $IFACE"
echo "WiFi mode: $IS_WIFI"
echo "Hostname: $(hostname)"
echo ""

# Step 1: Make scripts executable
echo "[1/7] Making scripts executable..."
chmod +x "$SCRIPT_DIR"/*.sh "$SCRIPT_DIR"/*.py 2>/dev/null || true
echo "  Done."

# Step 2: Create log directory
echo "[2/7] Creating log directory..."
sudo mkdir -p "$LOG_DIR"
sudo chown "$(whoami):$(whoami)" "$LOG_DIR"
echo "  Created $LOG_DIR"

# Step 3: Create config directory and copy AP map
echo "[3/7] Setting up config directory..."
sudo mkdir -p "$CONFIG_DIR"
if [[ -f "$SCRIPT_DIR/ap_map.txt" ]]; then
  sudo cp "$SCRIPT_DIR/ap_map.txt" "$CONFIG_DIR/"
  echo "  Copied ap_map.txt to $CONFIG_DIR/"
elif [[ -f "$SCRIPT_DIR/ap_map.txt.example" ]]; then
  sudo cp "$SCRIPT_DIR/ap_map.txt.example" "$CONFIG_DIR/ap_map.txt"
  echo "  Copied ap_map.txt.example to $CONFIG_DIR/ap_map.txt"
  echo "  NOTE: Edit $CONFIG_DIR/ap_map.txt with your actual BSSIDs"
else
  echo "  Warning: ap_map.txt not found, skipping"
fi

# Step 4: Generate appropriate crontab
echo "[4/7] Installing cron jobs..."

# Create a temporary crontab file
CRON_TMP=$(mktemp)

cat > "$CRON_TMP" << 'CRON_HEADER'
# Network Diagnostics Cron Jobs
# Auto-generated by install.sh

SHELL=/bin/bash
PATH=/usr/local/bin:/usr/bin:/bin
CRON_HEADER

# Add interface-specific variables
echo "IFACE=$IFACE" >> "$CRON_TMP"
echo "AP_MAP=$CONFIG_DIR/ap_map.txt" >> "$CRON_TMP"
echo "" >> "$CRON_TMP"

# Core network probes (work on both wired and wireless)
cat >> "$CRON_TMP" << CRON_NET
# === Core Network Probes (every minute) ===
* * * * * IFACE=\$IFACE $SCRIPT_DIR/net_probe.sh 2>/dev/null
* * * * * IFACE=\$IFACE $SCRIPT_DIR/wan_probe.sh 2>/dev/null

# === Failure Detection (every 5 minutes) ===
*/5 * * * * IFACE=\$IFACE $SCRIPT_DIR/on_failure_snapshot.sh 2>/dev/null

# === Bandwidth Tests (every 15 minutes) ===
# Uncomment and set SERVER_IP when you have an iperf3 server
# */15 * * * * SERVER_IP=<iperf-server-ip> $SCRIPT_DIR/iperf_probe.sh 2>/dev/null

# === Log Sync (every 5 minutes) ===
# Uncomment and set CENTRAL_HOST to enable log sync
# */5 * * * * CENTRAL_HOST=<central-pi-ip> CENTRAL_USER=pi $SCRIPT_DIR/sync_logs.sh 2>/dev/null
CRON_NET

# WiFi-specific probes (only if wireless)
if $IS_WIFI; then
  cat >> "$CRON_TMP" << CRON_WIFI

# === WiFi Probes (wireless only) ===
* * * * * IFACE=\$IFACE AP_MAP=\$AP_MAP $SCRIPT_DIR/wifi_probe.sh 2>/dev/null

# === AP Visibility Scan (every 10 minutes) ===
*/10 * * * * IFACE=\$IFACE AP_MAP=\$AP_MAP $SCRIPT_DIR/ap_scan.sh 2>/dev/null
CRON_WIFI
  echo "  Added WiFi probe jobs"
else
  echo "  Skipped WiFi probes (wired connection)"
fi

# Install crontab
crontab "$CRON_TMP"
rm "$CRON_TMP"
echo "  Cron jobs installed"

# Step 5: Install systemd service (WiFi only)
echo "[5/7] Setting up systemd service..."
if $IS_WIFI; then
  if [[ -f "$SCRIPT_DIR/netdiag-events.service" ]]; then
    sudo cp "$SCRIPT_DIR/netdiag-events.service" /etc/systemd/system/
    sudo systemctl daemon-reload
    sudo systemctl enable netdiag-events
    sudo systemctl start netdiag-events
    echo "  WiFi event watcher service installed and started"
  else
    echo "  Warning: netdiag-events.service not found, skipping"
  fi
else
  echo "  Skipped (not needed for wired connection)"
fi

# Step 6: Verify installation
echo "[6/7] Verifying installation..."
echo ""
echo "  Cron jobs:"
crontab -l | grep -c "netdiag" | xargs -I{} echo "    {} jobs installed"
echo ""

if $IS_WIFI; then
  echo "  Systemd service:"
  if systemctl is-active --quiet netdiag-events; then
    echo "    netdiag-events: running ✓"
  else
    echo "    netdiag-events: not running ✗"
  fi
  echo ""
fi

# Step 7: Summary
echo "[7/7] Installation complete!"
echo ""
echo "=========================================="
echo "  Summary for $(hostname)"
echo "=========================================="
echo ""
echo "  Interface: $IFACE ($( $IS_WIFI && echo 'WiFi' || echo 'Wired' ))"
echo "  Log directory: $LOG_DIR"
echo "  Config directory: $CONFIG_DIR"
echo ""
echo "  Scripts installed:"
if $IS_WIFI; then
  echo "    - net_probe.sh (every 1 min)"
  echo "    - wan_probe.sh (every 1 min)"
  echo "    - wifi_probe.sh (every 1 min)"
  echo "    - ap_scan.sh (every 10 min)"
  echo "    - on_failure_snapshot.sh (every 5 min)"
  echo "    - event_watch.sh (continuous via systemd)"
else
  echo "    - net_probe.sh (every 1 min)"
  echo "    - wan_probe.sh (every 1 min)"
  echo "    - on_failure_snapshot.sh (every 5 min)"
  echo "    (WiFi scripts skipped - wired connection)"
fi
echo ""
echo "  Next steps:"
echo "    1. Wait a few minutes for data to collect"
echo "    2. Check logs: ls -la $LOG_DIR"
echo "    3. To enable log sync, edit crontab: crontab -e"
echo "       and uncomment the sync_logs.sh line with your central Pi IP"
echo ""
if $IS_WIFI; then
  echo "    4. Edit $CONFIG_DIR/ap_map.txt with your actual BSSIDs:"
  echo "       sudo iw dev wlan0 scan | grep -E 'BSS|SSID'"
fi
echo ""
echo "=========================================="
